apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: DEX_STATIC_PASSWORD_HASH
              valueFrom:
                secretKeyRef:
                  name: dex-password
                  key: bcrypt-hash
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
